In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [60]:
digits = load_digits()

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3,random_state=42)

In [62]:
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9722222222222222

In [63]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.987037037037037

In [64]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9685185185185186

In [65]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [66]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [67]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [68]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [69]:
from sklearn.model_selection import StratifiedKFold

In [70]:
folds = StratifiedKFold(n_splits = 3)
score_l = []
score_svm = []
score_rf = []
for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_l.append( get_score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

print(score_l)
print(score_svm)
print(score_rf)

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9382303839732888, 0.9549248747913188, 0.9215358931552587]


In [71]:
from sklearn.model_selection import cross_val_score

In [72]:
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)


array([0.925     , 0.87777778, 0.93871866, 0.93593315, 0.89693593])

In [73]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [74]:

cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.91666667, 0.94986072, 0.9637883 , 0.91922006])